name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write

    if: ${{ github.repository_owner == 'charl-kruger' }}
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4

      - run: npm install

      - run: npm run build

      - id: changesets
        uses: changesets/action@v1
        with:
          version: ./.github/version-and-install.sh
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
